### ISSUE TITLE
cross-compile librarys like Tensorflow and opencv using host ubuntu 16.04 with cuda support to jetson nano

### ISSUE THREAD

**Issue by PythonImageDeveloper** [zhj-buffer/Cross-Compile-Jetson#5]
Hi,
I want to have crops-compiling from host ubuntu 16.04 with cuda support to jetson nano (jetpack 4.2.2 or 4.3) and then installing some libs like Tensorflow/opencv/nump and so on.
Is it possible to do this work? If so, can I modifiy your codes for my probelm?

**Comment by zhj-buffer** [comment]
I think you don't need extra the work. Download the sd-image for nano with jetpack 4.2.2. Then mount and chroot, the rest are the same as you did on X86 host.

**Comment by PythonImageDeveloper** [comment]
confige and instalizaion package for nano nearly takes 2.5 day. I save a lot of time using cross-compile ? and this way has don't problem for instaling of any packages?

**Comment by zhj-buffer** [comment]
Yes, you can install any deb packages as you did on the x86 host. You just can't run directly.
But install, update, remove, compile are experienced the same as host.
The things you need to care is the tools or the packages which can't install via the apt tools. It means you need to download the source code and compile yourself. But it's also ok because you have aready build a complete env for compiling.

**Comment by PythonImageDeveloper** [comment]
It's only used for installing deb files or it's possible for instaling whl file also?

**Comment by zhj-buffer** [comment]
Sure, only running is not support.
